import 'package:data_table_2/data_table_2.dart';
import 'package:flutter/material.dart';

class NewTable extends StatefulWidget {
  const NewTable({super.key});

  @override
  State<NewTable> createState() => _NewTableState();
}

class _NewTableState extends State<NewTable> {
  final ScrollController _scrollController = ScrollController();
  // final ScrollController scrollController = ScrollController();


  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Scrollbar(
        controller: _scrollController,
        thumbVisibility: true,
        trackVisibility: true,
        interactive: true,
        child: SingleChildScrollView(
          scrollDirection: Axis.vertical,
          controller: _scrollController,
          child: SingleChildScrollView(
            controller: _scrollController,
            scrollDirection: Axis.horizontal,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: DataTable(
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.black)
                ),
                showCheckboxColumn: true,
                sortColumnIndex: 1,
                border: TableBorder(
                  verticalInside:BorderSide(color: Colors.black87)
                ),
                dividerThickness: 2,
                columns: [
                  DataColumn(label: Container(
                    child: Text("Sl No"),
                    decoration: BoxDecoration(
                    border: Border.all(color: Colors.blue,)
                  ),)),
                  DataColumn(label: Text("nameaaaaaaaaaaaaaaaaaa")),
                  DataColumn(label: Text("nameaaaaaaaaaaaaaaaaaa")),
                  DataColumn(label: Text("nameaaaaaaaaaaaaaaaaaa")),
                  DataColumn(label: Text("nameaaaaaaaaaaaaaaaaaa")),
                  DataColumn(label: Text("nameaaaaaaaaaaaaaaaaaa")),
                  DataColumn(label: Text("nameaaaaaaaaaaaaaaaaaa")),
                  DataColumn(label: Text("nameaaaaaaaaaaaaaaaaaa")),
                  DataColumn(label: Text("nameaaaaaaaaaaaaaaaaaa")),
                  DataColumn(label: Text("nameaaaaaaaaaaaaaaaaaa")),
                  DataColumn(label: Text("nameaaaaaaaaaaaaaaaaaa")),
                ],
                rows: [
                  DataRow(cells: [
                    DataCell(Expanded(
                      child: Container(child: Text("yadu aaaaaaaaaa hhhhhhhh hhhhhhhhhhh aaaaaaaa"),
                      width: 50,),
                    )),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),
                  DataRow(cells: [
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                    DataCell(Text("yadu")),
                  ]),


                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
