name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch name that you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.9'  # Set your Flutter version

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          keep_files: true
          allow_empty_commit: false
          force_orphan: true
          branch: gh-pages  # Deploy to gh-pages branch
